export { default as RegisterSchema } from './register.schema'
export { default as LoginSchema } from './login.schema'
export { default as GoogleLoginSchema } from './googleLogin.schema'
export { default as ProductSchema } from './product.schema'
export { default as IDSchema } from './id.schema'
export { default as PlaceOrderSchema } from './placeOrder.schema'
export { default as PaymentSchema } from './payment.schema'
export { default as EmailSchema } from './email.schema'
